In [1]:
import numpy as np


Создаем массивы в np


In [2]:
my_list = [1,2,3,4,5]
my_arr = np.array(my_list)
my_arr
#Создали массив из обычного python list

array([1, 2, 3, 4, 5])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(my_matrix)
matrix
#Создали массив из обычного python list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
array = np.arange(0,10)
#Создаем массив чисел от 0 до 10 не включая 10. np.arange(начало диапазона, конец диапазона, шаг(необязательный аргумент))

In [5]:
array_zeros = np.zeros(5)
array_zeros
#Создали массив, заполненный 5 нулями.


array([0., 0., 0., 0., 0.])

In [6]:
array_zeros_matrix = np.zeros((5,5))
array_zeros_matrix
#Создали матрицу 5 на 5 (сначала строки, потом колонки)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
array_ones = np.ones(5)
array_ones
#Тоже самое, что и с нулями

array([1., 1., 1., 1., 1.])

In [8]:
new_array = np.linspace(0,10,3)
new_array
#Создали массив равноудаленных друг от друга чисел в диапазоне 10. np.linspace(начало диапазона, конеец диапазона, сколько равноудаленных друг от друга чисел(необязательный))
#Конец диапазона включен

array([ 0.,  5., 10.])

In [9]:
square_matrix = np.eye(3)
square_matrix
#Создает квадратную матрицу. np.eye(кол-во строчек и столбцов)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
random_numbers = np.random.rand(5)
random_numbers
#Создает 5 случайных чисел в диапазоне от 0 до 1

array([0.36208793, 0.79764482, 0.92452502, 0.73178265, 0.59044979])

In [11]:
random_numbers_matrix = np.random.rand(5,3)
random_numbers_matrix
#Создает случайную матрицу из 5 строк и 3 столбцов

array([[0.11130854, 0.19568486, 0.99297281],
       [0.78849201, 0.78331757, 0.19449553],
       [0.04506297, 0.72965203, 0.15636595],
       [0.964509  , 0.15904752, 0.17470977],
       [0.31234653, 0.61514152, 0.3001765 ]])

In [12]:
random_number_positive_and_negative = np.random.randn(5)
random_number_positive_and_negative
#Создает массив из случайных положительных и отрицательных чисел. Вероятность получить числа, близкие к 0 больше, т.к распределение нормальное

array([ 0.78535898, -2.0896362 , -0.7166915 , -0.5628029 , -0.00823613])

In [13]:
random_integers = np.random.randint(5,10,3)
random_integers
#Создает массив из 3 случайных целых чисел в диапазоне от 5 до 10. np.random.randint(начало диапазона, конец диапазона, сколько чисел) Верхняя граница не включена

array([9, 8, 6])

In [14]:
seed = np.random.seed(42)
seed_array = np.random.random(4)
seed_array
#Указываем 2 команды в одной ячейке. По сиду выводит 4 числа

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [15]:
arr = np.arange(0,25)
arr.reshape(5,5)
arr
#Сделали двумерный массив 5 на 5 из одномерного. Указываем размер, чтобы поместились все числа

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
ran_arr = np.random.randint(0,101,10)
ran_arr.max() #выводит максимальное число
ran_arr.min() #выводит мнимальное число число
ran_arr.argmax()#выводит индекс максимального числа
ran_arr.argmin()#выводит индекс минимального числа

7

Индексация и выборка


In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [20]:
arr[:5]

array([0, 1, 2, 3, 4])

In [21]:
arr[0:5] = 0,1,2,3,4
arr
#Broadcasting

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [23]:
arr_copy = arr.copy()
#Копия массива

In [24]:
array_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
array_2d[0]
#вывели первую строку матрицы

array([ 5, 10, 15])

In [26]:
array_2d[1][1]
#Вывели второй элемент второй строки

25

In [27]:
array_2d[0:2,1:]
#вывели второй и третий элемент первой и второй строки

array([[10, 15],
       [25, 30]])

In [28]:
arr = np.arange(1,11)
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
arr[bool_arr] #вывели все числа, соответствующие условию bool_arr

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr[arr > 4]
#Можно сразу условие внутри

array([ 5,  6,  7,  8,  9, 10])

Операции в NumPy

In [34]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr + 5 # к каждому элементу массива прибавили 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr + arr # сложение массивов

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr / arr # хоть на 0 нельзя делить, в NumPy выведит nan, а остальные разделит

<ipython-input-36-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [37]:
arr.sum()

45

In [38]:
arr.mean() # среднее значение массива

4.5

In [39]:
arr.var() # дисперсия

8.25

In [40]:
arr.std() # стандартное отклонение

2.8722813232690143

In [43]:
array_2d = np.arange(0,25).reshape(5,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
array_2d.sum() # сумма всех элементов матрицы

300

In [45]:
array_2d.sum(axis = 0) # сумма элементов по столбцам

array([50, 55, 60, 65, 70])

In [ ]:
array_2d.sum(axis = 1) # сумма элементов по строкам

Пишем тот axis, который хотим удалить
